git:
  depth: 10
notifications:
  email:
     on_success: always
     on_failure: always
language: csharp
solution: httpclienttest.sln
before_script:
  - dotnet --version
matrix:
  include:
  - os: linux
    dist: xenial
    mono: none
    dotnet: 2.1.401
    name: Ubuntu 16 (GCC 9) Native
    env:
      - BAM_BUILD_MODE=Native
      - BAM_TOOLCHAIN_NAME=Gcc
      - BAM_TOOLCHAIN_VERSION=9
